replicaCount: 1
profile: default
image:
  repository: acme
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations: {}
  labels: {}
ingress:
  enabled: true
  subdomain: acme
  basedomain: 127.0.0.1.nip.io
  hosts:
    - acme.opsnow.com
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels: {}
hpa:
  enabled: true
  min: 1
  max: 5
  cpu: 80
  mem: 80
resources:
  requests:
    cpu: 500m
    memory: 1024Mi
  limits:
    cpu: 600m
    memory: 2252Mi
readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 15
  failureThreshold: 6
livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 15
  failureThreshold: 6
configmap:
  enabled: false
secret:
  enabled: false
