# chart-version: latest

nameOverride: docker-registry

service:
  type: NodePort
  nodePort: 30500

ingress:
  enabled: true
  hosts:
    - docker-registry.127.0.0.1.nip.io
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    ingress.kubernetes.io/proxy-body-size: 500m
