replicaCount: 1
profile: default
image:
  repository: acme
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80
  annotations: {}
  labels: {}
ingress:
  enabled: true
  subdomain: acme
  basedomain: 127.0.0.1.nip.io
  hosts:
    - acme.opsnow.com
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  labels: {}
hpa:
  enabled: true
  min: 1
  max: 5
  cpu: 80
  mem: 80
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 120m
    memory: 153Mi
readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10
livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10
# livenessProbe:
#   exec:
#     command:
#     - cat
#     - /tmp/healthy
#   initialDelaySeconds: 5
#   periodSeconds: 10
# livenessProbe:
#   tcpSocket:
#     port: 80
#   initialDelaySeconds: 30
#   periodSeconds: 10
configmap:
  enabled: false
secret:
  enabled: false
